### ISSUE TITLE
Image Quality Issue

### ISSUE THREAD

**Issue by MaxtirError** [RenderMe-360/RenderMe-360#10]
Hi, I decode the rgb images from the smc file. It seems that the image quality is bad. There are many block artifacts in the image like this:

![image](https://github.com/RenderMe-360/RenderMe-360/assets/75169739/95925c8b-44a9-487f-8b00-ba55649555fe)
(cropped from the image from 0026 at the original resolution)

I wonder if this is right?

**Comment by pandongwei** [comment]
> Hi, I decode the rgb images from the smc file. It seems that the image quality is bad. There are many block artifacts in the image like this:
> 
> ![image](https://private-user-images.githubusercontent.com/75169739/329244206-95925c8b-44a9-487f-8b00-ba55649555fe.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc3NTIwODQsIm5iZiI6MTcxNzc1MTc4NCwicGF0aCI6Ii83NTE2OTczOS8zMjkyNDQyMDYtOTU5MjVjOGItNDRhOS00ODdmLThiMDAtYmE1NTY0OTU1NWZlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA3VDA5MTYyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIyMWM3ZjY0ZGM5OGJkNTg2YzIyYWQxYzI3NWNkOTIyMWNjZTYyYTAyNzhlMzg0ODI4M2EyM2Y4MmU0NjA4NWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.U31VL6S_hzvVEiHft01IPxXdKgNbxEKqav6ZwmXmTDc) (cropped from the image from 0026 at the original resolution)
> 
> I wonder if this is right?

Hello, 
i take 0026_e0_raw.smc as example and load & save the rgb image data as png file. The quality is ok, seen below:(no block artifacts)

![00000](https://github.com/RenderMe-360/RenderMe-360/assets/40038010/2c5df139-becd-49ec-976b-f2a70d5a8385)

Here is an example:
```python
path = "./0026_e0_raw.smc"  
smc = SMCReader(path)
imgs = smc.get_img('25','color', disable_tqdm=True)
for i, img in enumerate(imgs):
    print(img.shape)
    outpath = os.path.join(outdir, f"{i:05d}.png")
    cv2.imwrite(outpath, img)
```

**Comment by RenderMe-360** [comment]
Close issue as no reply.
