### ISSUE TITLE
About dataset download

### ISSUE THREAD

**Issue by prokaryote-hgy** [RenderMe-360/RenderMe-360#11]
您好！我在下载数据集时遇到以下问题

```
Fetching the list of datasets...
Downloading 1005 files: 
1. some_path/OpenXDLab___RenderMe-360/Face Attribute Annotation Statement.pdf already exists, jumping to next!
2. some_path/OpenXDLab___RenderMe-360/README.md already exists, jumping to next!
3. some_path/OpenXDLab___RenderMe-360/anno/0026/0026_e0_anno.smc already exists, jumping to next!
4. some_path/OpenXDLab___RenderMe-360/anno/0026/0026_e10_anno.smc already exists, jumping to next!
5. some_path/OpenXDLab___RenderMe-360/anno/0026/0026_e11_anno.smc already exists, jumping to next!
6. some_path/OpenXDLab___RenderMe-360/anno/0026/0026_e1_anno.smc already exists, jumping to next!
7. some_path/OpenXDLab___RenderMe-360/anno/0026/0026_e2_anno.smc already exists, jumping to next!
8. some_path/OpenXDLab___RenderMe-360/anno/0026/0026_e3_anno.smc already exists, jumping to next!
9. some_path/OpenXDLab___RenderMe-360/anno/0026/0026_e4_anno.smc already exists, jumping to next!
10. some_path/OpenXDLab___RenderMe-360/anno/0026/0026_e5_anno.smc already exists, jumping to next!
11. some_path/OpenXDLab___RenderMe-360/anno/0026/0026_e6_anno.smc already exists, jumping to next!
12. some_path/OpenXDLab___RenderMe-360/anno/0026/0026_e7_anno.smc already exists, jumping to next!
13. some_path/OpenXDLab___RenderMe-360/anno/0026/0026_e8_anno.smc already exists, jumping to next!
14. some_path/OpenXDLab___RenderMe-360/anno/0026/0026_e9_anno.smc already exists, jumping to next!
15. some_path/OpenXDLab___RenderMe-360/anno/0026/0026_h0_anno.smc already exists, jumping to next!
16. some_path/OpenXDLab___RenderMe-360/anno/0026/0026_s1_all_anno.smc already exists, jumping to next!
17. some_path/OpenXDLab___RenderMe-360/anno/0026/0026_s2_all_anno.smc already exists, jumping to next!
18. some_path/OpenXDLab___RenderMe-360/anno/0026/0026_s3_all_anno.smc already exists, jumping to next!
19. some_path/OpenXDLab___RenderMe-360/anno/0026/0026_s4_all_anno.smc already exists, jumping to next!
20. some_path/OpenXDLab___RenderMe-360/anno/0026/0026_s5_all_anno.smc already exists, jumping to next!
21. some_path/OpenXDLab___RenderMe-360/anno/0026/0026_s6_all_anno.smc already exists, jumping to next!
22. some_path/OpenXDLab___RenderMe-360/anno/0041/0041_e0_anno.smc already exists, jumping to next!
23. some_path/OpenXDLab___RenderMe-360/anno/0041/0041_e10_anno.smc already exists, jumping to next!
24. some_path/OpenXDLab___RenderMe-360/anno/0041/0041_e11_anno.smc already exists, jumping to next!
25. some_path/OpenXDLab___RenderMe-360/anno/0041/0041_e1_anno.smc already exists, jumping to next!
26. some_path/OpenXDLab___RenderMe-360/anno/0041/0041_e2_anno.smc already exists, jumping to next!
27. some_path/OpenXDLab___RenderMe-360/anno/0041/0041_e3_anno.smc already exists, jumping to next!
28. some_path/OpenXDLab___RenderMe-360/anno/0041/0041_e4_anno.smc already exists, jumping to next!
29. some_path/OpenXDLab___RenderMe-360/anno/0041/0041_e5_anno.smc already exists, jumping to next!
30. some_path/OpenXDLab___RenderMe-360/anno/0041/0041_e6_anno.smc already exists, jumping to next!
31. some_path/OpenXDLab___RenderMe-360/anno/0041/0041_e7_anno.smc already exists, jumping to next!
32. some_path/OpenXDLab___RenderMe-360/anno/0041/0041_e8_anno.smc already exists, jumping to next!
33. some_path/OpenXDLab___RenderMe-360/anno/0041/0041_e9_anno.smc already exists, jumping to next!
34. some_path/OpenXDLab___RenderMe-360/anno/0041/0041_h0_anno.smc already exists, jumping to next!
35. some_path/OpenXDLab___RenderMe-360/anno/0041/0041_s1_all_anno.smc already exists, jumping to next!
36. some_path/OpenXDLab___RenderMe-360/anno/0041/0041_s2_all_anno.smc already exists, jumping to next!
37. some_path/OpenXDLab___RenderMe-360/anno/0041/0041_s3_all_anno.smc already exists, jumping to next!
38. some_path/OpenXDLab___RenderMe-360/anno/0041/0041_s4_all_anno.smc already exists, jumping to next!
39. some_path/OpenXDLab___RenderMe-360/anno/0041/0041_s5_all_anno.smc already exists, jumping to next!
40. some_path/OpenXDLab___RenderMe-360/anno/0041/0041_s6_all_anno.smc already exists, jumping to next!
41. some_path/OpenXDLab___RenderMe-360/anno/0048/0048_e0_anno.smc already exists, jumping to next!
42. some_path/OpenXDLab___RenderMe-360/anno/0048/0048_e10_anno.smc already exists, jumping to next!
43. some_path/OpenXDLab___RenderMe-360/anno/0048/0048_e11_anno.smc already exists, jumping to next!
44. some_path/OpenXDLab___RenderMe-360/anno/0048/0048_e1_anno.smc already exists, jumping to next!
45. some_path/OpenXDLab___RenderMe-360/anno/0048/0048_e2_anno.smc already exists, jumping to next!
46. some_path/OpenXDLab___RenderMe-360/anno/0048/0048_e3_anno.smc already exists, jumping to next!
47. some_path/OpenXDLab___RenderMe-360/anno/0048/0048_e4_anno.smc already exists, jumping to next!
48. some_path/OpenXDLab___RenderMe-360/anno/0048/0048_e5_anno.smc already exists, jumping to next!
49. some_path/OpenXDLab___RenderMe-360/anno/0048/0048_e6_anno.smc already exists, jumping to next!
50. some_path/OpenXDLab___RenderMe-360/anno/0048/0048_e7_anno.smc already exists, jumping to next!
51. some_path/OpenXDLab___RenderMe-360/anno/0048/0048_e8_anno.smc already exists, jumping to next!
52. some_path/OpenXDLab___RenderMe-360/anno/0048/0048_e9_anno.smc already exists, jumping to next!
53. some_path/OpenXDLab___RenderMe-360/anno/0048/0048_h0_anno.smc already exists, jumping to next!
Total progress: 2%, total files:53/1005, downloaded size: 106.7G, total size: 6.1T
405: <!DOCTYPE html>
<html lang="zh-cn">

<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  <meta name="data-spm" content="a3c0e" />
  <title>405</title>
  <style>
    html, body, div, a, h2, p { margin: 0; padding: 0;  }
    a { text-decoration: none; color: #3b6ea3;  }
    .container { width: 1000px; margin: auto; color: #696969; }
    .header { padding: 50px 0; }
    .header .message { height: 36px; padding-left: 120px; background: url(https://errors.aliyun.com/images/TB1TpamHpXXXXaJXXXXeB7nYVXX-104-162.png) no-repeat 0 -128px; line-height: 36px; }
    .main { padding: 50px 0; background: #f4f5f7; }
    .main img { position: relative; left: 120px; }
    .footer { margin-top: 30px; text-align: right; }
    .footer a { padding: 8px 30px; border-radius: 10px; border: 1px solid #4babec; }
    .footer a:hover { opacity: .8; }
    .alert-shadow { display: none; position: absolute; top: 0; left: 0; width: 100%; height: 100%; background: #999; opacity: .5; }
    .alert { display: none; position: absolute; top: 200px; left: 50%; width: 600px; margin-left: -300px; padding-bottom: 25px; border: 1px solid #ddd; box-shadow: 0 2px 2px 1px rgba(0, 0, 0, .1); background: #fff; font-size: 14px; color: #696969; }
    .alert h2 {  margin: 0 2px; padding: 10px 15px 5px 15px; font-size: 14px; font-weight: normal; border-bottom: 1px solid #ddd; }
    .alert a { display: block; position: absolute; right: 10px; top: 8px; width: 30px; height: 20px; text-align: center; }
    .alert p {  padding: 20px 15px; }
  </style>
</head>

<body data-spm="7663354">
  <div data-spm="1998410538">
    <div class="header">
      <div class="container">
        <div class="message">
          很抱歉，由于您访问的URL有可能对网站造成安全威胁，您的访问被阻断。
          <div>您的请求ID是: <strong>
1a0c399d17166254579824776e005e</strong></div>
        </div>
      </div>
    </div>
    <div class="main">
      <div class="container">
        <img src="https://errors.aliyun.com/images/TB15QGaHpXXXXXOaXXXXia39XXX-660-117.png" />
      </div>
    </div>
    <div class="footer">
      <div class="container">
        <a target="_blank" id="report" href="javascript:;" data-spm-click="gostr=/waf.123.123;locaid=d001;">误报反馈</a>
      </div>
    </div>
  </div>
  <div id="alertShadow" class="alert-shadow"></div>
  <div id="alertContainer" class="alert">
    <h2>提示：<a href="javascript:;" title="关闭" id="closeAlert">X</a></h2>
    <p>感谢您的反馈，应用防火墙会尽快进行分析和确认。</p>
  </div>
  <script>
    function show() {
      var g = function(ele) { return document.getElementById(ele); };
      var reportHandle = g('report');
      var alertShadow = g('alertShadow');
      var alertContainer = g('alertContainer');
      var closeAlert = g('closeAlert');
      var own = {};
      own.report = function() {
        // SPM
        own.alert();
      };
      own.alert = function() {
        alertShadow.style.display = 'block';
        alertContainer.style.display = 'block';
      };
      own.close = function() {
        alertShadow.style.display = 'none';
        alertContainer.style.display = 'none';
      };
    };
  </script>
</body>

</html>
```

我使用以下命令进行下载

```
openxlab dataset get --dataset-repo OpenXDLab/RenderMe-360
```

**Comment by pandongwei** [comment]
> 您好！我在下载数据集时遇到以下问题
> 
> ```
> Fetching the list of datasets...
> Downloading 1005 files: 
> 1. some_path/OpenXDLab___RenderMe-360/Face Attribute Annotation Statement.pdf already exists, jumping to next!
> 2. some_path/OpenXDLab___RenderMe-360/README.md already exists, jumping to next!
> 3. some_path/OpenXDLab___RenderMe-360/anno/0026/0026_e0_anno.smc already exists, jumping to next!
> 4. some_path/OpenXDLab___RenderMe-360/anno/0026/0026_e10_anno.smc already exists, jumping to next!
> 5. some_path/OpenXDLab___RenderMe-360/anno/0026/0026_e11_anno.smc already exists, jumping to next!
> 6. some_path/OpenXDLab___RenderMe-360/anno/0026/0026_e1_anno.smc already exists, jumping to next!
> 7. some_path/OpenXDLab___RenderMe-360/anno/0026/0026_e2_anno.smc already exists, jumping to next!
> 8. some_path/OpenXDLab___RenderMe-360/anno/0026/0026_e3_anno.smc already exists, jumping to next!
> 9. some_path/OpenXDLab___RenderMe-360/anno/0026/0026_e4_anno.smc already exists, jumping to next!
> 10. some_path/OpenXDLab___RenderMe-360/anno/0026/0026_e5_anno.smc already exists, jumping to next!
> 11. some_path/OpenXDLab___RenderMe-360/anno/0026/0026_e6_anno.smc already exists, jumping to next!
> 12. some_path/OpenXDLab___RenderMe-360/anno/0026/0026_e7_anno.smc already exists, jumping to next!
> 13. some_path/OpenXDLab___RenderMe-360/anno/0026/0026_e8_anno.smc already exists, jumping to next!
> 14. some_path/OpenXDLab___RenderMe-360/anno/0026/0026_e9_anno.smc already exists, jumping to next!
> 15. some_path/OpenXDLab___RenderMe-360/anno/0026/0026_h0_anno.smc already exists, jumping to next!
> 16. some_path/OpenXDLab___RenderMe-360/anno/0026/0026_s1_all_anno.smc already exists, jumping to next!
> 17. some_path/OpenXDLab___RenderMe-360/anno/0026/0026_s2_all_anno.smc already exists, jumping to next!
> 18. some_path/OpenXDLab___RenderMe-360/anno/0026/0026_s3_all_anno.smc already exists, jumping to next!
> 19. some_path/OpenXDLab___RenderMe-360/anno/0026/0026_s4_all_anno.smc already exists, jumping to next!
> 20. some_path/OpenXDLab___RenderMe-360/anno/0026/0026_s5_all_anno.smc already exists, jumping to next!
> 21. some_path/OpenXDLab___RenderMe-360/anno/0026/0026_s6_all_anno.smc already exists, jumping to next!
> 22. some_path/OpenXDLab___RenderMe-360/anno/0041/0041_e0_anno.smc already exists, jumping to next!
> 23. some_path/OpenXDLab___RenderMe-360/anno/0041/0041_e10_anno.smc already exists, jumping to next!
> 24. some_path/OpenXDLab___RenderMe-360/anno/0041/0041_e11_anno.smc already exists, jumping to next!
> 25. some_path/OpenXDLab___RenderMe-360/anno/0041/0041_e1_anno.smc already exists, jumping to next!
> 26. some_path/OpenXDLab___RenderMe-360/anno/0041/0041_e2_anno.smc already exists, jumping to next!
> 27. some_path/OpenXDLab___RenderMe-360/anno/0041/0041_e3_anno.smc already exists, jumping to next!
> 28. some_path/OpenXDLab___RenderMe-360/anno/0041/0041_e4_anno.smc already exists, jumping to next!
> 29. some_path/OpenXDLab___RenderMe-360/anno/0041/0041_e5_anno.smc already exists, jumping to next!
> 30. some_path/OpenXDLab___RenderMe-360/anno/0041/0041_e6_anno.smc already exists, jumping to next!
> 31. some_path/OpenXDLab___RenderMe-360/anno/0041/0041_e7_anno.smc already exists, jumping to next!
> 32. some_path/OpenXDLab___RenderMe-360/anno/0041/0041_e8_anno.smc already exists, jumping to next!
> 33. some_path/OpenXDLab___RenderMe-360/anno/0041/0041_e9_anno.smc already exists, jumping to next!
> 34. some_path/OpenXDLab___RenderMe-360/anno/0041/0041_h0_anno.smc already exists, jumping to next!
> 35. some_path/OpenXDLab___RenderMe-360/anno/0041/0041_s1_all_anno.smc already exists, jumping to next!
> 36. some_path/OpenXDLab___RenderMe-360/anno/0041/0041_s2_all_anno.smc already exists, jumping to next!
> 37. some_path/OpenXDLab___RenderMe-360/anno/0041/0041_s3_all_anno.smc already exists, jumping to next!
> 38. some_path/OpenXDLab___RenderMe-360/anno/0041/0041_s4_all_anno.smc already exists, jumping to next!
> 39. some_path/OpenXDLab___RenderMe-360/anno/0041/0041_s5_all_anno.smc already exists, jumping to next!
> 40. some_path/OpenXDLab___RenderMe-360/anno/0041/0041_s6_all_anno.smc already exists, jumping to next!
> 41. some_path/OpenXDLab___RenderMe-360/anno/0048/0048_e0_anno.smc already exists, jumping to next!
> 42. some_path/OpenXDLab___RenderMe-360/anno/0048/0048_e10_anno.smc already exists, jumping to next!
> 43. some_path/OpenXDLab___RenderMe-360/anno/0048/0048_e11_anno.smc already exists, jumping to next!
> 44. some_path/OpenXDLab___RenderMe-360/anno/0048/0048_e1_anno.smc already exists, jumping to next!
> 45. some_path/OpenXDLab___RenderMe-360/anno/0048/0048_e2_anno.smc already exists, jumping to next!
> 46. some_path/OpenXDLab___RenderMe-360/anno/0048/0048_e3_anno.smc already exists, jumping to next!
> 47. some_path/OpenXDLab___RenderMe-360/anno/0048/0048_e4_anno.smc already exists, jumping to next!
> 48. some_path/OpenXDLab___RenderMe-360/anno/0048/0048_e5_anno.smc already exists, jumping to next!
> 49. some_path/OpenXDLab___RenderMe-360/anno/0048/0048_e6_anno.smc already exists, jumping to next!
> 50. some_path/OpenXDLab___RenderMe-360/anno/0048/0048_e7_anno.smc already exists, jumping to next!
> 51. some_path/OpenXDLab___RenderMe-360/anno/0048/0048_e8_anno.smc already exists, jumping to next!
> 52. some_path/OpenXDLab___RenderMe-360/anno/0048/0048_e9_anno.smc already exists, jumping to next!
> 53. some_path/OpenXDLab___RenderMe-360/anno/0048/0048_h0_anno.smc already exists, jumping to next!
> Total progress: 2%, total files:53/1005, downloaded size: 106.7G, total size: 6.1T
> 405: <!DOCTYPE html>
> <html lang="zh-cn">
> 
> <head>
>   <meta charset="utf-8">
>   <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
>   <meta name="data-spm" content="a3c0e" />
>   <title>405</title>
>   <style>
>     html, body, div, a, h2, p { margin: 0; padding: 0;  }
>     a { text-decoration: none; color: #3b6ea3;  }
>     .container { width: 1000px; margin: auto; color: #696969; }
>     .header { padding: 50px 0; }
>     .header .message { height: 36px; padding-left: 120px; background: url(https://errors.aliyun.com/images/TB1TpamHpXXXXaJXXXXeB7nYVXX-104-162.png) no-repeat 0 -128px; line-height: 36px; }
>     .main { padding: 50px 0; background: #f4f5f7; }
>     .main img { position: relative; left: 120px; }
>     .footer { margin-top: 30px; text-align: right; }
>     .footer a { padding: 8px 30px; border-radius: 10px; border: 1px solid #4babec; }
>     .footer a:hover { opacity: .8; }
>     .alert-shadow { display: none; position: absolute; top: 0; left: 0; width: 100%; height: 100%; background: #999; opacity: .5; }
>     .alert { display: none; position: absolute; top: 200px; left: 50%; width: 600px; margin-left: -300px; padding-bottom: 25px; border: 1px solid #ddd; box-shadow: 0 2px 2px 1px rgba(0, 0, 0, .1); background: #fff; font-size: 14px; color: #696969; }
>     .alert h2 {  margin: 0 2px; padding: 10px 15px 5px 15px; font-size: 14px; font-weight: normal; border-bottom: 1px solid #ddd; }
>     .alert a { display: block; position: absolute; right: 10px; top: 8px; width: 30px; height: 20px; text-align: center; }
>     .alert p {  padding: 20px 15px; }
>   </style>
> </head>
> 
> <body data-spm="7663354">
>   <div data-spm="1998410538">
>     <div class="header">
>       <div class="container">
>         <div class="message">
>           很抱歉，由于您访问的URL有可能对网站造成安全威胁，您的访问被阻断。
>           <div>您的请求ID是: <strong>
> 1a0c399d17166254579824776e005e</strong></div>
>         </div>
>       </div>
>     </div>
>     <div class="main">
>       <div class="container">
>         <img src="https://errors.aliyun.com/images/TB15QGaHpXXXXXOaXXXXia39XXX-660-117.png" />
>       </div>
>     </div>
>     <div class="footer">
>       <div class="container">
>         <a target="_blank" id="report" href="javascript:;" data-spm-click="gostr=/waf.123.123;locaid=d001;">误报反馈</a>
>       </div>
>     </div>
>   </div>
>   <div id="alertShadow" class="alert-shadow"></div>
>   <div id="alertContainer" class="alert">
>     <h2>提示：<a href="javascript:;" title="关闭" id="closeAlert">X</a></h2>
>     <p>感谢您的反馈，应用防火墙会尽快进行分析和确认。</p>
>   </div>
>   <script>
>     function show() {
>       var g = function(ele) { return document.getElementById(ele); };
>       var reportHandle = g('report');
>       var alertShadow = g('alertShadow');
>       var alertContainer = g('alertContainer');
>       var closeAlert = g('closeAlert');
>       var own = {};
>       own.report = function() {
>         // SPM
>         own.alert();
>       };
>       own.alert = function() {
>         alertShadow.style.display = 'block';
>         alertContainer.style.display = 'block';
>       };
>       own.close = function() {
>         alertShadow.style.display = 'none';
>         alertContainer.style.display = 'none';
>       };
>     };
>   </script>
> </body>
> 
> </html>
> ```
> 
> 我使用以下命令进行下载
> 
> ```
> openxlab dataset get --dataset-repo OpenXDLab/RenderMe-360
> ```

你好，这种通常是网络问题，建议换更换网络再尝试。

**Comment by Vincento-Wang** [comment]
same problem ! how to solve it. @pandongwei

**Comment by pandongwei** [comment]
> same problem ! how to solve it. @pandongwei

Hi,
We provide a new way to download the data in google drive, please refer to https://renderme-360.github.io/inner-download.html#Download for the application.
