### ISSUE TITLE
Downloading issue

### ISSUE THREAD

**Issue by DreamtaleCore** [RenderMe-360/RenderMe-360#3]
Hi there,
I encountered some problems while downloading the dataset. Below is the error message. How should I solve it?
<img width="1010" alt="image" src="https://github.com/RenderMe-360/RenderMe-360/assets/12713528/10483023-107b-4dce-88ed-13f1057e626e">
It looks like a server firewall issue.

**Comment by pandongwei** [comment]
Hi, 
Please try to download the data again and feedback the exact time. We need to check the download history to see which firewall rule was hit.

**Comment by pandongwei** [comment]
> Hi there, I encountered some problems while downloading the dataset. Below is the error message. How should I solve it? <img alt="image" width="1010" src="https://private-user-images.githubusercontent.com/12713528/306209889-10483023-107b-4dce-88ed-13f1057e626e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA0MDQ2MjcsIm5iZiI6MTcxMDQwNDMyNywicGF0aCI6Ii8xMjcxMzUyOC8zMDYyMDk4ODktMTA0ODMwMjMtMTA3Yi00ZGNlLTg4ZWQtMTNmMTA1N2U2MjZlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE0VDA4MTg0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM0ODAzMjY5NGYwY2M2MWQxMjk3NDUyZDA5YWFhMmZmZDQ0Y2MyMDRhYzBkNWZmNzgwNTVlOTFhYTY0ODUxMDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Nb14WqK5OdEl4hTaXjdmWO3CZj4aO8XTULNWEt6o3yY"> It looks like a server firewall issue.

Hi,
Please try to download the data again and feedback the exact time. We need to check the download history to see which firewall rule was hit.

**Comment by pandongwei** [comment]
close the issue as no more reply.
