### ISSUE TITLE
No calibration data

### ISSUE THREAD

**Issue by naivenaive** [RenderMe-360/RenderMe-360#5]
Calibration data cannot be found in the smc files such as 0026_e0_raw.smc. How to get the calibration data? Thanks!

**Comment by Yifehuang97** [comment]
Hi, I am not fimiliar with the smc data. Is the raw head scan avaliable in the raw data? Also how can I check the smc data? Thank you!

**Comment by naivenaive** [comment]
I find the calibration data in the anno smc files

**Comment by Yifehuang97** [comment]
Thanks for your reply. I am not fimiliar with smc files. Can you give me a simple instruction on how to view such file? Thank you!

**Comment by pandongwei** [comment]
> Thanks for your reply. I am not fimiliar with smc files. Can you give me a simple instruction on how to view such file? Thank you!

Hi, we provide a script to read the smc file, which you can find from the page:https://renderme-360.github.io/inner-download.html#Download
Here is the download link: https://renderme-360.github.io/assets/code/renderme_360_reader.py

**Comment by Yifehuang97** [comment]
Thank you!
