### ISSUE TITLE
Extrinsic: World to Cam or Cam to World?

### ISSUE THREAD

**Issue by naivenaive** [RenderMe-360/RenderMe-360#6]
The extrinsic data is available in the anno smc file. However, the convention of the extrinsic is not specified explicitly. Is it a matrix for transformation from world coordinate to camera coordinate or the opposite? Please provide a clarification on this issue. Thanks.

**Comment by acseker** [comment]
Can you also explain which coordinate system is being used and whether the transformation matrix is in row- or column-major order? Thanks.

**Comment by pandongwei** [comment]
> The extrinsic data is available in the anno smc file. However, the convention of the extrinsic is not specified explicitly. Is it a matrix for transformation from world coordinate to camera coordinate or the opposite? Please provide a clarification on this issue. Thanks.

Hi, the extrinsic data is a 4x4 matrix that represents the transformation from camera coordinate to the world coordinate. We have provided the clarification of the data from https://renderme-360.github.io/inner-download.html#Download, please check for details.

**Comment by Vincento-Wang** [comment]
> > The extrinsic data is available in the anno smc file. However, the convention of the extrinsic is not specified explicitly. Is it a matrix for transformation from world coordinate to camera coordinate or the opposite? Please provide a clarification on this issue. Thanks.
> 
> Hi, the extrinsic data is a 4x4 matrix that represents the transformation from camera coordinate to the world coordinate. We have provided the clarification of the data from https://renderme-360.github.io/inner-download.html#Download, please check for details.

{
    "cameraID"{
        "K"                                 : double (3,3) intrinsic matrix,
        "D"                                 : double (5,) distortion coeffient,
        "RT"                                : double (4,4) maps point from camera to world
    }
}

World_xyz = (RT @ np.linalg.inv(K) @ uv) , is this translation all right ? I use this formulation for projection, but cannot get multi-view projection onto the same point(e.g. mouth center)

how can I get the depth value ? 
e.g.
![image](https://github.com/user-attachments/assets/3782b6ca-a578-4641-9e83-2d5d890b16ad)

**Comment by pandongwei** [comment]
> > > The extrinsic data is available in the anno smc file. However, the convention of the extrinsic is not specified explicitly. Is it a matrix for transformation from world coordinate to camera coordinate or the opposite? Please provide a clarification on this issue. Thanks.
> > 
> > 
> > Hi, the extrinsic data is a 4x4 matrix that represents the transformation from camera coordinate to the world coordinate. We have provided the clarification of the data from https://renderme-360.github.io/inner-download.html#Download, please check for details.
> 
> { "cameraID"{ "K" : double (3,3) intrinsic matrix, "D" : double (5,) distortion coeffient, "RT" : double (4,4) maps point from camera to world } }
> 
> World_xyz = (RT @ np.linalg.inv(K) @ uv) , is this translation all right ? I use this formulation for projection, but cannot get multi-view projection onto the same point(e.g. mouth center)
> 
> how can I get the depth value ? e.g. ![image](https://private-user-images.githubusercontent.com/175805671/352908729-3782b6ca-a578-4641-9e83-2d5d890b16ad.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIzMTAxOTAsIm5iZiI6MTcyMjMwOTg5MCwicGF0aCI6Ii8xNzU4MDU2NzEvMzUyOTA4NzI5LTM3ODJiNmNhLWE1NzgtNDY0MS05ZTgzLTJkNWQ4OTBiMTZhZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDczMFQwMzI0NTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wZjgyNmUxOGUxZjI0Nzc3N2RjNDJkOGZkNmIyNzZiMTJkMTEwZTcwNjQ0NzAyNjNiZjExYjBkNGUzNjVmMmU2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Uo13uq7lVzkpura_Z9QSEVA2VAnRxUgdIaG0cG34utk)

To get the depth value, you need to process the multiview data with triangulation (https://en.wikipedia.org/wiki/Triangulation) ,but not only translate the single view uv data. So your translation to get xyz_world is not correct.

**Comment by Vincento-Wang** [comment]
> > > > The extrinsic data is available in the anno smc file. However, the convention of the extrinsic is not specified explicitly. Is it a matrix for transformation from world coordinate to camera coordinate or the opposite? Please provide a clarification on this issue. Thanks.

> > > 
> > > 
> > > Hi, the extrinsic data is a 4x4 matrix that represents the transformation from camera coordinate to the world coordinate. We have provided the clarification of the data from https://renderme-360.github.io/inner-download.html#Download, please check for details.
> > 
> > 
> > { "cameraID"{ "K" : double (3,3) intrinsic matrix, "D" : double (5,) distortion coeffient, "RT" : double (4,4) maps point from camera to world } }
> > World_xyz = (RT @ np.linalg.inv(K) @ uv) , is this translation all right ? I use this formulation for projection, but cannot get multi-view projection onto the same point(e.g. mouth center)
> > how can I get the depth value ? e.g. ![image](https://private-user-images.githubusercontent.com/175805671/352908729-3782b6ca-a578-4641-9e83-2d5d890b16ad.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIzMTAxOTAsIm5iZiI6MTcyMjMwOTg5MCwicGF0aCI6Ii8xNzU4MDU2NzEvMzUyOTA4NzI5LTM3ODJiNmNhLWE1NzgtNDY0MS05ZTgzLTJkNWQ4OTBiMTZhZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDczMFQwMzI0NTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wZjgyNmUxOGUxZjI0Nzc3N2RjNDJkOGZkNmIyNzZiMTJkMTEwZTcwNjQ0NzAyNjNiZjExYjBkNGUzNjVmMmU2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Uo13uq7lVzkpura_Z9QSEVA2VAnRxUgdIaG0cG34utk)
> 
> To get the depth value, you need to process the multiview data with triangulation (https://en.wikipedia.org/wiki/Triangulation) ,but not only translate the single view uv data. So your translation to get xyz_world is not correct.

I use depth z = 1.217, with the point near the nose(i guess the world coordinate origin, maybe at the sitting floor)  then use the above mentioned method to do the projection, all of the views see the point on the nose, proved it correct, thanks. 

![image](https://github.com/user-attachments/assets/cf95ddfa-2a0c-4336-9d6b-b60302631daf)
![image](https://github.com/user-attachments/assets/2c3b943c-2629-4791-90c2-4da34cdc50e8)
![image](https://github.com/user-attachments/assets/d293eafb-4982-4bff-8f79-3a9f12d8cfb3)
![image](https://github.com/user-attachments/assets/49a4fa14-9366-4032-8e6e-d44ac46f4db4)
