### ISSUE TITLE
More IDs?

### ISSUE THREAD

**Issue by neeek2303** [RenderMe-360/RenderMe-360#7]
Hi and thank you a lot for your work! 

I'm wondering when are you going to add more IDs? The website says 500 IDs should be ready by March 2024
<img width="977" alt="Screenshot 2024-04-04 at 12 41 12" src="https://github.com/RenderMe-360/RenderMe-360/assets/60851662/617a1536-9e82-4785-908c-37b02a9be55b">

**Comment by mingliangfu** [comment]
Looking forward to the release of more sampled IDs.

**Comment by pandongwei** [comment]
> Hi and thank you a lot for your work!
> 
> I'm wondering when are you going to add more IDs? The website says 500 IDs should be ready by March 2024 <img alt="Screenshot 2024-04-04 at 12 41 12" width="977" src="https://private-user-images.githubusercontent.com/60851662/319568219-617a1536-9e82-4785-908c-37b02a9be55b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMxODE5NTUsIm5iZiI6MTcxMzE4MTY1NSwicGF0aCI6Ii82MDg1MTY2Mi8zMTk1NjgyMTktNjE3YTE1MzYtOWU4Mi00Nzg1LTkwOGMtMzdiMDJhOWJlNTViLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE1VDExNDczNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFiYTdmNmIzNDFmNWE3YzkxMWJjNDNiMzQ5ZDY5NzcyMThhZDc4MGY5MzkwMWRlZWUzZDFmMWUwYzYyMTk2YzEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.43-pdOSHP7L6zpJcpwGAPyzDOf0G0wOyrGtMgfJDn0k">

Thank you for your interest in our dataset. We are working hard to process the data and plan to release the full amount of 500id data before the end of June 2024 (if everything goes well, it will be in May)
